<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bookstore [
<!ELEMENT bookstore (title,author_name,ISBN_no,publisher_name,edition,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author_name (#PCDATA)>
<!ELEMENT ISBN_no (#PCDATA)>
<!ELEMENT publisher_name (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<bookstore>
	<book>
		<title>a</title>
		<author_name>b</author_name>
		<ISBN_no>c</ISBN_no>
		<publisher_name>d</publisher_name>
		<edition>e</edition>
		<price>f</price>
	</book>
	
	<book>
		<title>a</title>
		<author_name>b</author_name>
		<ISBN_no>c</ISBN_no>
		<publisher_name>d</publisher_name>
		<edition>e</edition>
		<price>f</price>
	</book>
	
	<book>
		<title>a</title>
		<author_name>b</author_name>
		<ISBN_no>c</ISBN_no>
		<publisher_name>d</publisher_name>
		<edition>e</edition>
		<price>f</price>
	</book>
</bookstore>